### PR TITLE
First try avoiding SortingObject

### PR DESCRIPTION
**Pull request by DanBaDo**
I can't build my own protocol from Sorting nor my own class from SortingObject, so I write my own protocol and class. I it the way I must take?

### CODE REVIEW

**Review by gaal1le0 — CHANGES_REQUESTED** [review]
It wasn't the task, you have changed the initial files and create your own structure. The best approach to accomplish the task would have been create an `Equatable` protocol that determinate when two models are equal. If you look at your code it's only valid for `Person` object not for any object, moreover, your class has the responsability of understand when a person is greater that other. 

Your solution only fix the problem to a specific data structure with a lot of coupling. Your class has tons of responsibilities which shouldn't have. 

Tomorrow I will give more light into the deep well. If you want you can try again and prepare another code to accomplish this task, if not you can wait until tomorrow to understand what solution is the best.  

I know this exercise is too difficult, I really appreciate your attempt to achieve the aim but it's not the perfect one.

**Comment by DanBaDo** [comment]
So, we are talking about it: https://stackoverflow.com/questions/51924509/typescript-generic-implementation
Isn't it?

**Comment by gaal1le0** [comment]
Exactly

**Comment by DanBaDo** [comment]
I hope it fits better with requirements.
This commint shows a error in intex.ts line 21: Property 'age' does not exist on type 'Person'.
But Person class in line 13 has a 'age' property as well Person interface in Person.ts.

**Review by gaal1le0 — CHANGES_REQUESTED** [review]
Hi again Daniel!!!

It's not exactly the best result but it's nearer than before. I recommend you to take extra attention in today coding weekend, I will take into more detail about generics types and what is conform an object to a determinate protocol. I really appreciate your new attempt but it isn't the right answer. Trying to summarize, it has less coupling that before but it present a lot of coupling yet. Don't worry if you want you can try again before this afternoon and I will check it again. :). 

PD: You are the unique that has been able to deliver some code in this exercises, congratulations :)

**Comment by DanBaDo** [comment]
Today I search for multiple inheritance in typescript and found a solution for two problems yesterday I don't: declare functions as types and and mixins.
https://stackoverflow.com/a/53296512
I suppose these are then main lackes in my proposal.

**Comment by gaal1le0** [comment]
The example you provided from StackOverflow has a lot of coupling and not match the requirements.

**Comment by DanBaDo** [comment]
Ok. A new one.
Now class gets methods through constructor.
Finally I couldn't attend yesterday session. 
I hope can see the video later.

**Comment by gaal1le0** [comment]
It has also some coupling, you are getting an approach that can get really serious problems in the future. You need to change your approach. I recommend you to start from draft. When you think on a approach you need to think in the future and how will you maintain this code.

**Comment by DanBaDo** [comment]
Well. I know you want I find a specific solution, but haven't idea what's the direction you spect I take.

**Comment by gaal1le0** [comment]
Okey. Let's try another approach. Please base your code in the last coding weekend example and start from that point. Only create a method that can allow you to compare two persons and decided where one is greater that other, then please make a push and mention me here using comments, I will take a look about this part and I will give you more instructions to get a final solution. What do you think? @DanBaDo

**Pull request closed without merging**
